### PR TITLE
Fix typo: code to get .py filename from .pyc

### PR DESCRIPTION
**Pull request by pfmoore**
I haven't actually tested this, but I spotted it on reading the code :-)

### CODE REVIEW

**Comment by uranusjr** [comment]
Ooooops

(I guess this also indicates the code isn’t really useful? I don’t know.)

**Comment by pfmoore** [comment]
Well, I was looking this weekend at writing something very similar, and then found out about this. So it's useful to me, if no-one else :-)

A couple of things I was planning on doing in my own code, which I'd be interested in knowing if they'd fit with what you'd want in this project:

1. A call to get information back about an environment (is it a virtualenv, what is the "base" Python interpreter it was created from, was it created using venv or virtualenv).
2. Rather than just create an environment with the interpreter requested, use the above to always create from the "base" Python - this would avoid the weird issues caused by creating a venv from a virtualenv, etc.

I'm happy to do these as PRs for here rather than as a separate project, if that suits you :-)

**Comment by uranusjr** [comment]
I definitely thought about 2. (and I believe this depends on 1.), but gave up in the end due to practicality. AFAICT both venv and virtualenv are able to do this on their own (`pyvenv.cfg` and `sys.real_prefix`), but things go south once you start nesting one inside another. I would be most thrilled if you can make it work!

**Comment by pfmoore** [comment]
The biggest practical problem, I suspect, is getting from a `sys.prefix` value (which is what `real_prefix` and `base_prefix` give) back to an executable name. Looking for `<prefix>/python` on Unix, and `<prefix>/python.exe` on Windows may be sufficient, if we can trace the links back to a non-virtual environment (which I believe we should be able to do). But there's a fair number of potential special cases that might need to be considered (not least of which are the whole python2/python3 mess, and whatever "interesting" peculiarities Linux distributions might have chosen to inflict on us - as someone with limited Linux experience, I don't know how bad this could be...)

It may even be worth a feature request to virtualenv and venv to add a "base executable" attribute that we *could* rely on.

**Comment by uranusjr** [comment]
IIRC `sysconfig` is able to report a correct executable path (I forget exactly which function; on my phone right now).  virtualenv is unable to do the same,  it sure why), but it could be possible with some site.py hacks.

**Pull request merged**
